name: u217733_medbook
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - arabic_reshaper
  - asgiref
  - asn1crypto
  - asttokens
  - backcall
  - bcrypt
  - biopython
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - click
  - colorama
  - comm
  - configparser
  - cryptography
  - cssselect2
  - cycler
  - dbus
  - debugpy
  - decorator
  - django
  - django-crispy-forms
  - django-filter
  - django-widget-tweaks
  - entrypoints
  - executing
  - expat
  - faker
  - fftw
  - fontconfig
  - fonttools
  - freetype
  - fribidi
  - future
  - giflib
  - glib
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - html5lib
  - icu
  - idna
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libedit
  - libevent
  - libffi
  - libgfortran5
  - liblapack
  - libllvm10
  - libopenblas
  - libpng
  - libpq
  - libsodium
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libxslt
  - lxml
  - lz4-c
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - munkres
  - ncurses
  - nest-asyncio
  - nspr
  - nss
  - numexpr
  - numpy
  - openssl
  - oscrypto
  - packaging
  - pandas
  - pango
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - ply
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pydyf
  - pygments
  - pyhanko
  - pyhanko-certvalidator
  - pyopenssl
  - pyparsing
  - pypdf3
  - pyphen
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-bidi
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - pytz-deprecation-shim
  - pyyaml
  - pyzmq
  - qrcode
  - qt
  - qt-main
  - qt-webengine
  - qtwebkit
  - readline
  - reportlab
  - requests
  - scipy
  - seaborn
  - setuptools
  - sip
  - six
  - sqlite
  - sqlparse
  - stack_data
  - svglib
  - text-unidecode
  - tinycss2
  - tk
  - toml
  - tornado
  - tqdm
  - traitlets
  - tzdata
  - tzlocal
  - uritools
  - urllib3
  - wcwidth
  - weasyprint
  - webencodings
  - wheel
  - xhtml2pdf
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - uwsgi