# Generated by Django 4.1 on 2023-02-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allergens', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_id', models.CharField(max_length=10)),
                ('short_desciption', models.CharField(max_length=100)),
                ('long_desciption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('birthday', models.DateField()),
                ('heigth', models.CharField(max_length=5)),
                ('weigth', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField()),
                ('position', models.CharField(choices=[('NURSE', 'NURSE'), ('DOCTOR', 'DOCTOR'), ('RECEPTIONIST', 'RECEPTIONIST')], max_length=100)),
                ('department', models.CharField(choices=[('Emergency', 'Emergency'), ('Intensive Care', 'Intensive Care'), ('Surgery', 'Surgery'), ('Radiology', 'Radiology'), ('Laboratory', 'Laboratory'), ('Physical Therapy', 'Physical Therapy'), ('Pharmacy', 'Pharmacy'), ('Mental Health', 'Mental Health'), ('Oncology', 'Oncology'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Dermatology', 'Dermatology'), ('Ophthalmology', 'Ophthalmology'), ('Rheumatology', 'Rheumatology'), ('Pulmonology', 'Pulmonology'), ('Infectious Diseases', 'Infectious Diseases'), ('Nephrology', 'Nephrology'), ('General', 'General')], max_length=100)),
            ],
        ),
    ]
