# Generated by Django 4.1 on 2023-02-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_patient_id_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_id',
            new_name='id',
        ),
    ]
