# Generated by Django 4.1 on 2023-02-05 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_staff_id_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHasAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ManyToManyField(to='accounts.allergen')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
            ],
        ),
    ]
