# Generated by Django 4.1 on 2023-02-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patienthasallergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition_Check_UP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heigth', models.CharField(max_length=5)),
                ('weigth', models.CharField(max_length=5)),
                ('urgency', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('abnormal_breathing', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('smokes', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('drinks', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('has_headache', models.CharField(choices=[('Yes', 'Yes'), ('Sometimes', 'Sometimes'), ('No', 'No')], max_length=15)),
                ('mental_state', models.CharField(choices=[('Stable', 'Stable'), ('Mildly distressed', 'Mildly distressed'), ('Moderately distressed', 'Moderately distressed'), ('Severely distressed', 'Severely distressed'), ('Acutely psychotic', 'Acutely psychotic')], max_length=50)),
                ('heart_rate', models.CharField(max_length=20)),
                ('blood_presure', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='heigth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weigth',
        ),
        migrations.CreateModel(
            name='PatientHasDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('treatment', models.CharField(max_length=500)),
                ('check_up_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.condition_check_up')),
                ('dignosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.diagnosis')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staff')),
            ],
        ),
        migrations.CreateModel(
            name='NextAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='accounts.staff')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient')),
                ('receptionits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptionist', to='accounts.staff')),
            ],
        ),
        migrations.AddField(
            model_name='condition_check_up',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patient'),
        ),
    ]
