# Generated by Django 4.1 on 2023-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_condition_check_up_remove_patient_heigth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition_check_up',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
