# Generated by Django 4.1 on 2023-03-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextappointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
