# Generated by Django 4.1 on 2023-03-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_nextappointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthasallergy',
            old_name='patient',
            new_name='pid',
        ),
    ]
